/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ToolboxNetworkData {
  rpc?: Rpc[];
  indexing?: Indexing[];
  explorer?: Explorer[];
  oracle?: Oracle[];
  bridge?: Bridge[];
  devTool?: DevTool[];
  faucet?: Faucet[];
  analytic?: Analytic[];
  wallet?: Wallet[];
}
export interface Rpc {
  slug: string;
  provider: string;
  plan: string;
  nodeType: string;
  chain: string;
  address: string | null;
  accessPrice: string | null;
  queryPrice: string | null;
  uptimeSla: string | null;
  bandwidthSla: string | null;
  blocksBehindSla: string | null;
  starred: boolean;
  trial: boolean;
  availableApis: string[] | null;
  limitations: string[] | null;
  securityImprovements: string[] | null;
  monitoringAndAnalytics: string[] | null;
  regions: string[] | null;
  verifiedUptime: string | null;
  verifiedLatency: string | null;
  verifiedBlocksBehindAvg: string | null;
  actionButtons: string[] | null;
}
export interface Indexing {
  slug: string;
  provider: string;
  chain: string;
  address: string | null;
  technology: string;
  plan: string;
  trial: boolean;
  accessPrice: string | null;
  queryPrice: string | null;
  uptimeSla: string | null;
  bandwidthSla: string | null;
  blocksBehindSla: string | null;
  supportSla: string | null;
  starred: boolean;
  availableApis: string[] | null;
  limitations: string[] | null;
  securityImprovements: string[] | null;
  monitoringAndAnalytics: string[] | null;
  regions: string[] | null;
  additionalFeatures: string[] | null;
  verifiedUptime: string | null;
  verifiedLatency: string | null;
  verifiedBlocksBehindAvg: string | null;
  actionButtons: string[] | null;
}
export interface Explorer {
  slug: string;
  provider: string;
  chain: string;
  technology: string;
  monitoringAndAnalytics: string[] | null;
  additionalFeatures: string[] | null;
  starred: boolean;
  availableApis: string[] | null;
  sdk: string[] | null;
  searchCapabilities: string[] | null;
  smartContractsVerifications: boolean;
  fullHistory: boolean;
  pricing: string | null;
  actionButtons: string[] | null;
}
export interface Oracle {
  slug: string;
  provider: string;
  chain: string;
  technology: string;
  accessPrice: string | null;
  queryPrice: string | null;
  starred: boolean;
  availableApis: string[] | null;
  monitoringAndAnalytics: string[] | null;
  additionalFeatures: string[] | null;
  dataTypes: string[] | null;
  decentralizationModel: string | null;
  economicalSecurity: boolean;
  economicalSecurityNote: string | null;
  sdk: string[] | null;
  auditsPerformed: string[] | null;
  actionButtons: string[] | null;
}
export interface Bridge {
  slug: string;
  provider: string;
  chain: string;
  technology: string;
  openSource: boolean;
  support: string[] | null;
  supportedChains: string[] | null;
  starred: boolean;
  availableApis: string[] | null;
  monitoringAndAnalytics: string[] | null;
  additionalFeatures: string[] | null;
  assetTypes: string[] | null;
  txSpeedSla: string | null;
  throughputSla: string | null;
  price: string | null;
  economicalSecurity: boolean;
  economicalSecurityNote: string | null;
  auditsPerformed: string[] | null;
  decentralizationModel: string | null;
  sdk: string[] | null;
  actionButtons: string[] | null;
}
export interface DevTool {
  slug: string;
  provider: string;
  toolType: string;
  price: string | null;
  tag: string[] | null;
  description: string | null;
  starred: boolean;
  actionButtons: string[] | null;
}
export interface Faucet {
  slug: string;
  provider: string;
  chain: string;
  requiresLogin: boolean;
  hasCaptcha: boolean;
  requiredMainnetBalance: string | null;
  price: string | null;
  dripLimitAmount: string | null;
  dripLimitPeriod: string | null;
  additionalNotes: string[] | null;
  starred: boolean;
  actionButtons: string[] | null;
}
export interface Analytic {
  slug: string;
  provider: string;
  chain: string;
  dataSources: string[] | null;
  hasDashboard: boolean;
  availableApis: string[] | null;
  price: string | null;
  starred: boolean;
  actionButtons: string[] | null;
}
export interface Wallet {
  slug: string;
  provider: string;
  openSource: boolean;
  supportedPlatforms: string[] | null;
  custodial: boolean;
  mfa: boolean;
  msig: boolean;
  hardware: boolean;
  keyExport: boolean;
  native: boolean;
  evm: boolean;
  tendermint: boolean;
  tokensSupport: string[] | null;
  staking: boolean;
  price: string | null;
  support: string[] | null;
  audit: string[] | null;
  languages: string[] | null;
  starred: boolean;
  actionButtons: string[] | null;
}
